// Code generated by Slice Machine. DO NOT EDIT.

import AboutImg from './AboutImg/index.svelte';
import InfoBlock from './InfoBlock/index.svelte';
import NameText from './NameText/index.svelte';

export const components = {
	about_img: AboutImg,
	info_block: InfoBlock,
	name_text: NameText
};
