// Code generated by Slice Machine. DO NOT EDIT.

import InfoBlock from './InfoBlock/index.svelte';
import ListThings from './ListThings/index.svelte';
import SecTitle from './SecTitle/index.svelte';
import TitleMain from './TitleMain/index.svelte';

export const components = {
	info_block: InfoBlock,
	list_things: ListThings,
	sec_title: SecTitle,
	title_main: TitleMain
};
