// Code generated by Slice Machine. DO NOT EDIT.

import AboutImg from './AboutImg/index.svelte';
import SubTitle from './SubTitle/index.svelte';
import Title from './Title/index.svelte';

export const components = {
	about_img: AboutImg,
	sub_title: SubTitle,
	title: Title
};
